import {StyleSheet} from 'react-native';
import {Colors} from '../../constants/Colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.WHITE_PRIMARY,
  },
  containerMain: {
    backgroundColor: Colors.WHITE_PRIMARY,
    flex: 1,
    paddingBottom: 5,
  },
  titleContainer: {
    flexDirection: 'row',
  },
  ListLotContainer: {
    flex: 1,
    flexDirection: 'row',
    borderBlockColor: 'black',
    paddingLeft: 16,
    paddingRight: 16,
  },
  ImageContainer: {
    paddingRight: 16,
    width: 120,
    height: 120,
  },
  lotDescr: {
    flex: 1,
    justifyContent: 'space-between',
    paddingRight: 25,
  },
  separator: {
    marginVertical: 8,
    borderBottomColor: Colors.GRAY_DARK,
    borderBottomWidth: 1,
    marginHorizontal: 16,
    paddingHorizontal: 10,
  },
  image: {
    width: '100%',
    height: 120,
  },
  timer: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
  },
  time: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingLeft: 7,
    paddingRight: 7,
    backgroundColor: Colors.BLUE_EXTRA_LIGHT,
    borderRadius: 4,
  },
  bet: {
    marginTop: 15,
  },
  price: {
    flexDirection: 'row',
    gap: 20,
  },
  tabsContainer: {
    flexDirection: 'row',
    backgroundColor: Colors.WHITE_PRIMARY,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: Colors.BLACK_PRIMARY,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 8,
  },
  tabHideContainer: {
    height: 60,
    overflow: 'hidden',
    marginTop: 0,
    paddingTop: 0,
    paddingBottom: 1,
  },
  tab: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 3,
    borderRadius: 20,
    marginVertical: 8,
    marginHorizontal: 5,
    borderWidth: 1,
    borderColor: Colors.GRAY_PRIMARY,
  },
  title: {
    textAlign: 'center',
    fontSize: 16,
    fontWeight: '400',
    fontFamily: 'IBM Plex Sans',
  },
  btnContainer: {
    position: 'relative',
  },
  btn: {
    position: 'absolute',
    right: 7,
    bottom: 65,
    borderRadius: 50,
    width: 45,
  },
  listFooterContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingLeft: 14,
  },
  listFooterPickCount: {
    width: 55,
    position: 'absolute',
    top: -115,
    left: 18,
    alignItems: 'center',
    backgroundColor: Colors.WHITE_PRIMARY,
    paddingVertical: 5,
    paddingHorizontal: 3,
  },
  listFooterPages: {
    width: 65,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  listFooterLoadMoreContainer: {
    flex: 3,
    paddingHorizontal: 15,
    paddingVertical: 5,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: 10,
  },
  listFooterPickPage: {
    width: '100%',
    height: 30,
    position: 'absolute',
    top: '-80%',
    left: 14,
    alignItems: 'center',
    backgroundColor: Colors.WHITE_PRIMARY,
  },
  listFooterCurrPage: {
    width: 45,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
